apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spacelaunchnow.app
  namespace: default
spec:
  secretName: spacelaunchnow-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: spacelaunchnow.app
  dnsNames:
  - status.spacelaunchnow.app
  - grafana.spacelaunchnow.app
  - dev.spacelaunchnow.app
  - vault.spacelaunchnow.app
  - argo.spacelaunchnow.app
  - spacelaunchnow.app