apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spacelaunchnow.me
spec:
  secretName: spacelaunchnow-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: spacelaunchnow.me
  dnsNames:
  - k8-dev.spacelaunchnow.me
  - spacelaunchnow.me
  - pypi.spacelaunchnow.me
  - grafana.spacelaunchnow.me