apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cjones@spacelaunchnow.me
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
    - dns01:
        cloudflare:
          email: cjones@spacelaunchnow.me
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token