apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-global-issuer
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: cjones@spacelaunchnow.me
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - dns01:
        cloudflare:
          email: cjones@spacelaunchnow.me
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token