{{- if .Values.notification_service.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django.fullname" . }}-notification-service
  labels:
    {{- include "django.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification_service
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "django.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: notification_service
  template:
    metadata:
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        tag: "{{ .Values.image.tag }}"
      labels:
        {{- include "django.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: notification_service
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: ["python", "manage.py", "run_notification_service"]
          {{- if .Values.notification_service.args }}
          args: {{- toYaml .Values.notification_service.args | nindent 10}}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            limits:
              cpu: 50m
              memory: 256Mi
            requests:
              cpu: 5m
              memory: 32Mi
          env:
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: django-secret-key
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: database-password
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: database-username
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: database-host
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: database-port
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: email-host-user
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: email-host-password
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: google-api-key
            - name: GOOGLE_ANALYTICS_TRACKING_ID
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: google-analytics-tracking-id
            - name: TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: token-key
            - name: TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: token-secret
            - name: CONSUMER_KEY
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: consumer-key
            - name: CONSUMER_SECRET
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: consumer-secret
            - name: FCM_KEY
              valueFrom:
                secretKeyRef:
                  name: sln-auth-prod
                  key: fcm-key
            - name: SERVER_ROLE
              value: "worker"
          envFrom:
            - secretRef:
                name: {{ include "django.fullname" . }}
            - configMapRef:
                name: {{ include "django.fullname" . }}-notification-service
{{- end }}