apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sln-dev

resources:
  - namespace.yaml

commonLabels:
  environment: staging
  app.kubernetes.io/name: spacelaunchnow
  app.kubernetes.io/instance: staging

images:
  - name: registry.digitalocean.com/sln-prod-registry-01/space-launch-now-base
    newTag: staging
