# Default values for django.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.digitalocean.com/sln-prod-registry-01/space-launch-now-base
  tag: staging
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  normal:
    DEBUG: "False"
    DATABASE_ENGINE: "django.db.backends.postgresql"
    DATABASE_NAME: "LL2_staging_01"
    CACHE_BACKEND: "django.core.cache.backends.memcached.PyMemcacheCache"
    CACHE_LOCATION: "sln-staging-memcached-memcached.sln-dev.svc.cluster.local:11211"
    DISABLE_THROTTLE: "True"
    STORAGE_BUCKET_NAME: "thespacedevs-dev"
    AWS_S3_ENDPOINT_URL: "https://nyc3.digitaloceanspaces.com"
    EMAIL_HOST: "smtp.gmail.com"
    EMAIL_PORT: "587"
    EMAIL_HOST_TLS: "True"
    SLN_ENVIRONMENT: "staging"
    ENABLE_SILKY: "False"
    SILKY_INTERCEPT_PERCENT: "100"
    SILKY_ANALYZE_QUERIES: "False"
    HOST_NAME: "staging.spacelaunchnow.app"

  worker:
    IS_WEBSERVER: "False"
    IS_API: "False"
    IS_ADMIN: "False"
  web:
    IS_WEBSERVER: "True"
    IS_API: "True"
    IS_ADMIN: "True"
  service:
    IS_WEBSERVER: "False"
    IS_API: "False"
    IS_ADMIN: "False"


web:
  replicaCount: 1
  port: 8080
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 1
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  budget:
    minAvailable: 1 # Ignored when replicaCount is 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
    # podAntiAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #   - weight: 100
    #     podAffinityTerm:
    #       labelSelector:
    #         matchExpressions:
    #         - key: app.kubernetes.io/instance
    #           operator: In
    #           values:
    #           - glitchtip-prod-web
    #       topologyKey: kubernetes.io/hostname
  livenessProbe:
    failureThreshold: 10
    initialDelaySeconds: 5
    timeoutSeconds: 2
    path: "/_health/"
  readinessProbe:
    failureThreshold: 10
    initialDelaySeconds: 5
    timeoutSeconds: 2
    path: "/_health/"
  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    className: ""
    annotations:
     kubernetes.io/ingress.class: nginx
     cert-manager.io/cluster-issuer: letsencrypt-production
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: staging.spacelaunchnow.app
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: spacelaunchnow-tls
        hosts:
          - staging.spacelaunchnow.app

notification_service:
  enabled: false

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
