# Generated by Django 4.2.11 on 2024-03-05 03:39

from django.db import migrations, models

import app.models
import custom_storages


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appconfig",
            name="navigation_drawer_image",
            field=models.FileField(
                blank=True,
                default=None,
                null=True,
                storage=custom_storages.AppImageStorage,
                upload_to=app.models.image_path,
            ),
        ),
        migrations.AlterField(
            model_name="nationality",
            name="flag",
            field=models.FileField(storage=custom_storages.AppImageStorage, upload_to=app.models.language_image_path),
        ),
        migrations.AlterField(
            model_name="staff",
            name="profile",
            field=models.FileField(storage=custom_storages.AppImageStorage, upload_to=app.models.profile_image_path),
        ),
    ]
