exclude: >
  (?x)^(
      .idea|
      migrations/.*\.py|
      src/tools/.*\.py
  )$
default_language_version:
  python: python3.6.8
repos:
  - repo: https://github.com/pycqa/isort
    rev: fd5ba70665a37ec301a1f714ed09336048b3be63  # frozen: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: e3000ace2fd1fcb1c181bb7a8285f1f976bcbdc7  # frozen: 21.7b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: dcd740bc0ebaf2b3d43e59a0060d157c97de13f3  # frozen: 3.9.2
    hooks:
      - id: flake8