version: 2
registries:
  spacelaunchnow:
    type: python-index
    url: "https://pypi.spacelaunchnow.me/simple/"
    username: ${{ secrets.PRIVATE_USERNAME }}
    password: ${{ secrets.PRIVATE_PASSWORD }}
updates:
  - package-ecosystem: "pip"
    directory: "/"
    registries:
      - spacelaunchnow # Allow version updates for dependencies in this registry
    schedule:
      interval: "monthly"