version: '3'

services:
  rabbitmq:
    container_name: slns-rabbitmq
    hostname: slns-rabbitmq
    image: rabbitmq:latest
    networks:
      - main
    ports:
      - "5672:5672"
    restart: on-failure

  slns-celery_worker:
    command: sh -c "celery -A spacelaunchnow worker -l info"
    depends_on:
    - rabbitmq
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    hostname: slns-celery_worker
    image: spacelaunchnow-server:latest
    networks:
    - main
    restart: on-failure

  slns-celery_beat:
    command: sh -c "celery -A spacelaunchnow beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    container_name: slns-celery_beat
    depends_on:
    - rabbitmq
    hostname: slns-celery_beat
    image: spacelaunchnow-server:latest
    networks:
    - main
    restart: on-failure

networks:
  main: