version: '3'
volumes:
  gunicorn_socket1:
  gunicorn_socket2:
  gunicorn_socket3:
services:
  web1:
    container_name: slns-web1
    image: registry.calebjones.dev:5050/sln-server:production
    deploy:   
      restart_policy:
        condition: always
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - gunicorn_socket1:/gunicorn_socket
      - /etc/letsencrypt/:/ssl/
      - ./log/web1:/code/log
    command: gunicorn -b unix:/gunicorn_socket/socket spacelaunchnow.wsgi --workers 2 --threads 1
    labels:
      - "io.portainer.accesscontrol.teams=Space Launch Now"
  web2:
    container_name: slns-web2
    image: registry.calebjones.dev:5050/sln-server:production
    deploy:   
      restart_policy:
        condition: always
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - gunicorn_socket2:/gunicorn_socket
      - /etc/letsencrypt/:/ssl/
      - ./log/web2:/code/log
    command: gunicorn -b unix:/gunicorn_socket/socket spacelaunchnow.wsgi --workers 2 --threads 1
    labels:
      - "io.portainer.accesscontrol.teams=Space Launch Now"
  web3:
    container_name: slns-web3
    image: registry.calebjones.dev:5050/sln-server:production
    deploy:   
      restart_policy:
        condition: always
    sysctls:
      net.core.somaxconn: 1024
    volumes:
      - gunicorn_socket3:/gunicorn_socket
      - /etc/letsencrypt/:/ssl/
      - ./log/web3:/code/log
    command: gunicorn -b unix:/gunicorn_socket/socket spacelaunchnow.wsgi --workers 1 --threads 1
    labels:
      - "io.portainer.accesscontrol.teams=Space Launch Now"
  memcached:
    container_name: slns-cache
    image: memcached:latest
    labels:
      - "io.portainer.accesscontrol.teams=Space Launch Now"
    deploy:   
      restart_policy:
        condition: always
    entrypoint:
      - memcached
      - -m 64
    ports:
      - "11211:11211"
    expose:
      - "11211"
    depends_on:
      - web1
      - web2
      - web3
  nginx:
    container_name: slns-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    deploy:   
      restart_policy:
        condition: always
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - gunicorn_socket1:/gunicorn_socket1
      - gunicorn_socket2:/gunicorn_socket2
      - gunicorn_socket3:/gunicorn_socket3
      - /home/cjones/:/ssl/
      - ./log/nginx:/var/log/nginx
    labels:
      - "io.portainer.accesscontrol.teams=Space Launch Now"
    depends_on:
      - web1
      - web2
      - web3
