# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 05:24
from __future__ import unicode_literals

import api.models
import custom_storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configurations', '0004_firststagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('country_code', models.CharField(blank=True, default='', max_length=255)),
                ('abbrev', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('info_url', models.URLField(blank=True, null=True)),
                ('wiki_url', models.URLField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=2048, null=True)),
                ('launchers', models.CharField(blank=True, default='', max_length=500)),
                ('orbiters', models.CharField(blank=True, default='', max_length=500)),
                ('administrator', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('founding_year', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('legacy_image_url', models.URLField(blank=True, default=None, null=True)),
                ('legacy_nation_url', models.URLField(blank=True, default=None, null=True)),
                ('image_url', models.FileField(blank=True, default=None, null=True, storage=custom_storages.AgencyImageStorage(), upload_to=api.models.image_path)),
                ('logo_url', models.FileField(blank=True, default=None, null=True, storage=custom_storages.LogoStorage(), upload_to=api.models.logo_path)),
                ('nation_url', models.FileField(blank=True, default=None, null=True, storage=custom_storages.AgencyNationStorage(), upload_to=api.models.nation_path)),
                ('agency_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='configurations.AgencyType')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_agencies', to='api.Agency')),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
                'ordering': ['name', 'featured'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('feature_image', models.FileField(blank=True, default=None, null=True, storage=custom_storages.EventImageStorage(), upload_to=api.models.image_path)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FirstStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reused', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Info URL',
                'verbose_name_plural': 'Info URLs',
            },
        ),
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.NullBooleanField(default=False)),
                ('success', models.NullBooleanField()),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('landing_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing', to='configurations.LandingLocation')),
                ('landing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing', to='configurations.LandingType')),
            ],
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('launch_library', models.NullBooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('net', models.DateTimeField(max_length=255, null=True)),
                ('window_end', models.DateTimeField(max_length=255, null=True)),
                ('window_start', models.DateTimeField(max_length=255, null=True)),
                ('inhold', models.NullBooleanField(default=False)),
                ('tbdtime', models.NullBooleanField(default=False)),
                ('tbddate', models.NullBooleanField(default=False)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('holdreason', models.CharField(blank=True, max_length=255, null=True)),
                ('failreason', models.CharField(blank=True, max_length=255, null=True)),
                ('hashtag', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Launch',
                'verbose_name_plural': 'Launches',
            },
        ),
        migrations.CreateModel(
            name='Launcher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=10, null=True)),
                ('flight_proven', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=255)),
                ('details', models.CharField(blank=True, default='', max_length=2048)),
            ],
            options={
                'verbose_name': 'Launch Vehicle',
                'verbose_name_plural': 'Launch Vehicles',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='LauncherConfig',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('reusable', models.BooleanField(default=False)),
                ('audited', models.BooleanField(default=False)),
                ('librarian_notes', models.CharField(blank=True, default='', max_length=2048)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('family', models.CharField(blank=True, default='', max_length=200)),
                ('full_name', models.CharField(blank=True, default='', max_length=200)),
                ('variant', models.CharField(blank=True, default='', max_length=200)),
                ('alias', models.CharField(blank=True, default='', max_length=200)),
                ('launch_cost', models.CharField(blank=True, max_length=200, null=True, verbose_name='Launch Cost ($)')),
                ('maiden_flight', models.DateField(blank=True, max_length=255, null=True, verbose_name='Maiden Flight Date')),
                ('min_stage', models.IntegerField(blank=True, null=True)),
                ('max_stage', models.IntegerField(blank=True, null=True)),
                ('length', models.FloatField(blank=True, null=True, verbose_name='Length (m)')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='Max Diameter (m)')),
                ('fairing_diameter', models.FloatField(blank=True, null=True, verbose_name='Max Fairing Diameter (m)')),
                ('launch_mass', models.IntegerField(blank=True, null=True, verbose_name='Mass at Launch (T)')),
                ('leo_capacity', models.IntegerField(blank=True, null=True, verbose_name='LEO Capacity (kg)')),
                ('gto_capacity', models.IntegerField(blank=True, null=True, verbose_name='GTO Capacity (kg)')),
                ('geo_capacity', models.IntegerField(blank=True, null=True, verbose_name='GEO Capacity (kg)')),
                ('sso_capacity', models.IntegerField(blank=True, null=True, verbose_name='SSO Capacity (kg)')),
                ('to_thrust', models.IntegerField(blank=True, null=True, verbose_name='Thrust at Liftoff (kN)')),
                ('apogee', models.IntegerField(blank=True, null=True, verbose_name='Apogee - Sub-Orbital Only (km)')),
                ('vehicle_range', models.IntegerField(blank=True, null=True, verbose_name='Vehicle Range - Legacy')),
                ('info_url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('wiki_url', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('legacy_image_url', models.CharField(blank=True, default='', max_length=200)),
                ('image_url', models.FileField(blank=True, default=None, null=True, storage=custom_storages.LauncherImageStorage(), upload_to=api.models.image_path)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('launch_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launcher_list', to='api.Agency')),
            ],
            options={
                'verbose_name': 'Launcher Configurations',
                'verbose_name_plural': 'Launcher Configurations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('country_code', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('type_name', models.CharField(blank=True, default='', max_length=255)),
                ('mission_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='configurations.MissionType')),
                ('orbit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='configurations.Orbit')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
            },
        ),
        migrations.CreateModel(
            name='Orbiter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('agency', models.CharField(default='Unknown', max_length=200)),
                ('history', models.CharField(default='', max_length=1000)),
                ('details', models.CharField(default='', max_length=1000)),
                ('in_use', models.BooleanField(default=True)),
                ('capability', models.CharField(default='', max_length=2048)),
                ('maiden_flight', models.DateField(max_length=255, null=True)),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Length (m)')),
                ('diameter', models.FloatField(blank=True, null=True, verbose_name='Diameter (m)')),
                ('human_rated', models.BooleanField(default=False)),
                ('crew_capacity', models.IntegerField(blank=True, null=True, verbose_name='Crew Capacity')),
                ('payload_capacity', models.IntegerField(blank=True, null=True, verbose_name='Payload Capacity (kg)')),
                ('flight_life', models.CharField(blank=True, max_length=2048, null=True)),
                ('wiki_link', models.URLField(blank=True)),
                ('info_link', models.URLField(blank=True)),
                ('image_url', models.FileField(blank=True, default=None, null=True, storage=custom_storages.OrbiterImageStorage(), upload_to=api.models.image_path)),
                ('nation_url', models.FileField(blank=True, default=None, null=True, storage=custom_storages.AgencyNationStorage(), upload_to=api.models.image_path)),
                ('launch_agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orbiter_list', to='api.Agency')),
            ],
            options={
                'verbose_name': 'Spacecraft',
                'verbose_name_plural': 'Spacecraft',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('agency_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('info_url', models.URLField(blank=True, null=True)),
                ('wiki_url', models.URLField(blank=True, null=True)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pad', to='api.Location')),
            ],
            options={
                'verbose_name': 'Pad',
                'verbose_name_plural': 'Pads',
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('type_name', models.CharField(blank=True, default='', max_length=255)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='api.Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocket', to='api.LauncherConfig')),
            ],
        ),
        migrations.CreateModel(
            name='SecondStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondstage', to='api.Landing')),
                ('launcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondstage', to='api.Launcher')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondstage', to='api.Rocket')),
            ],
        ),
        migrations.CreateModel(
            name='VidURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_url', models.URLField()),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid_urls', to='api.Launch')),
            ],
            options={
                'verbose_name': 'Video URL',
                'verbose_name_plural': 'Video URLs',
            },
        ),
        migrations.AddField(
            model_name='launcher',
            name='launcher_config',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launcher', to='api.LauncherConfig'),
        ),
        migrations.AddField(
            model_name='launch',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='api.Mission'),
        ),
        migrations.AddField(
            model_name='launch',
            name='pad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='api.Pad'),
        ),
        migrations.AddField(
            model_name='launch',
            name='rocket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Rocket'),
        ),
        migrations.AddField(
            model_name='launch',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='configurations.LaunchStatus'),
        ),
        migrations.AddField(
            model_name='infourls',
            name='launch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_urls', to='api.Launch'),
        ),
        migrations.AddField(
            model_name='firststage',
            name='landing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firststage', to='api.Landing'),
        ),
        migrations.AddField(
            model_name='firststage',
            name='launcher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firststage', to='api.Launcher'),
        ),
        migrations.AddField(
            model_name='firststage',
            name='rocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firststage', to='api.Rocket'),
        ),
        migrations.AddField(
            model_name='firststage',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='firststage', to='configurations.FirstStageType'),
        ),
    ]
