# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=1048),
        ),
    ]
