# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcher',
            name='agency',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='launcher',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='launcherdetail',
            name='LVInfo',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='launcherdetail',
            name='agency',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='launcherdetail',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='orbiter',
            name='agency',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='orbiter',
            name='details',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='orbiter',
            name='history',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='orbiter',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
