# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170727_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launcher',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='launcher',
            old_name='nationURL',
            new_name='nation_url',
        ),
        migrations.RenameField(
            model_name='orbiter',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='orbiter',
            old_name='nationURL',
            new_name='nation_url',
        ),
        migrations.RenameField(
            model_name='orbiter',
            old_name='wikiLink',
            new_name='wiki_link',
        ),
        migrations.RemoveField(
            model_name='launcherdetail',
            name='LVInfo',
        ),
        migrations.RemoveField(
            model_name='launcherdetail',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='launcherdetail',
            name='imageURL',
        ),
        migrations.RemoveField(
            model_name='launcherdetail',
            name='nationURL',
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='alias',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='apogee',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='diameter',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='family',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='gto_capacity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='info_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='launch_mass',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='length',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='leo_capacity',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='manufacturer',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='max_stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='min_stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='range',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='s_family',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='to_thrust',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='variant',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='vehicle_class',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='wiki_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
