# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181106_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='failreason',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='hashtag',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='holdreason',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='img_url',
            field=models.CharField(blank=True, max_length=1048, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='name',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='launch',
            name='slug',
            field=models.SlugField(max_length=1048, unique=True),
        ),
        migrations.AlterField(
            model_name='launcher',
            name='status',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AlterField(
            model_name='payload',
            name='name',
            field=models.CharField(blank=True, default='', max_length=1048),
        ),
    ]
