# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-31 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170731_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launcherdetail',
            old_name='range',
            new_name='vehicle_range',
        ),
    ]
