# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181106_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcherconfig',
            name='librarian_notes',
            field=models.CharField(blank=True, default='', max_length=2048, null=True),
        ),
    ]
