# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20181122_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astronauts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('born', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=2048)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Agency')),
            ],
        ),
        migrations.CreateModel(
            name='AstronautStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Orbiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=2048)),
                ('orbiter_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrbiterConfiguration')),
            ],
        ),
        migrations.CreateModel(
            name='OrbiterFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splashdown', models.DateTimeField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('landing_crew', models.ManyToManyField(blank=True, related_name='landing_crew', to='api.Astronauts')),
                ('launch_crew', models.ManyToManyField(blank=True, related_name='launch_crew', to='api.Astronauts')),
                ('onboard_crew', models.ManyToManyField(blank=True, related_name='onboard_crew', to='api.Astronauts')),
                ('orbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Orbiter')),
                ('rocket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orbiterflight', to='api.Rocket')),
            ],
        ),
        migrations.CreateModel(
            name='OrbiterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('founded', models.DateField()),
                ('description', models.CharField(max_length=2048)),
                ('orbit', models.CharField(max_length=255)),
                ('crew', models.ManyToManyField(blank=True, to='api.Astronauts')),
                ('docked_vehicles', models.ManyToManyField(blank=True, to='api.Orbiter')),
            ],
        ),
        migrations.AddField(
            model_name='orbiter',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrbiterStatus'),
        ),
        migrations.AddField(
            model_name='astronauts',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AstronautStatus'),
        ),
    ]
