# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0005_astronautstatus_orbiterstatus_spacestationstatus'),
        ('api', '0004_auto_20181122_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Astronauts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('born', models.DateField()),
                ('nationality', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('bio', models.CharField(max_length=2048)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Agency')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.AstronautStatus')),
            ],
            options={
                'verbose_name': 'Astronaut',
                'verbose_name_plural': 'Astronauts',
            },
        ),
        migrations.CreateModel(
            name='Orbiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=2048)),
                ('orbiter_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrbiterConfiguration')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.OrbiterStatus')),
            ],
            options={
                'verbose_name': 'Orbiter',
                'verbose_name_plural': 'Orbiters',
            },
        ),
        migrations.CreateModel(
            name='OrbiterFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splashdown', models.DateTimeField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('landing_crew', models.ManyToManyField(blank=True, related_name='landing_crew', to='api.Astronauts')),
                ('launch_crew', models.ManyToManyField(blank=True, related_name='launch_crew', to='api.Astronauts')),
                ('onboard_crew', models.ManyToManyField(blank=True, related_name='onboard_crew', to='api.Astronauts')),
                ('orbiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Orbiter')),
                ('rocket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='orbiterflight', to='api.Rocket')),
            ],
            options={
                'verbose_name': 'Orbiter Flight',
                'verbose_name_plural': 'Orbiter Flights',
            },
        ),
        migrations.CreateModel(
            name='SpaceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('founded', models.DateField()),
                ('description', models.CharField(max_length=2048)),
                ('orbit', models.CharField(max_length=255)),
                ('crew', models.ManyToManyField(blank=True, to='api.Astronauts')),
                ('docked_vehicles', models.ManyToManyField(blank=True, related_name='spacestation', to='api.Orbiter')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Agency')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.SpaceStationStatus')),
            ],
            options={
                'verbose_name': 'Space Station',
                'verbose_name_plural': 'Space Stations',
            },
        ),
    ]
