# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170731_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='launcher',
            options={'verbose_name': 'Launcher', 'verbose_name_plural': 'Launchers'},
        ),
        migrations.AlterModelOptions(
            name='launcherdetail',
            options={'verbose_name': 'Launcher Detail', 'verbose_name_plural': 'Launcher Details'},
        ),
        migrations.AlterModelOptions(
            name='orbiter',
            options={'verbose_name': 'Orbiter', 'verbose_name_plural': 'Orbiters'},
        ),
    ]
