# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171130_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launcherdetail',
            old_name='manufacturer',
            new_name='agency',
        ),
    ]
