# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20171213_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=2048)),
                ('launchers', models.CharField(default='', max_length=500)),
                ('orbiters', models.CharField(default='', max_length=500)),
                ('image_url', models.URLField(blank=True)),
                ('nation_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Launch Agency',
                'verbose_name_plural': 'Launch Agencies',
            },
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='launch_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Agency'),
        ),
        migrations.AddField(
            model_name='orbiter',
            name='launch_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Agency'),
        ),
    ]
