# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20171213_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='launcher',
            options={'verbose_name': 'Launcher (Legacy)', 'verbose_name_plural': 'Launchers (Legacy)'},
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
