# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20171213_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='launchers',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='agency',
            name='orbiters',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
