# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '00010_astronauts_populate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronauts',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
