# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-13 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20171213_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcherdetail',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
