# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20181128_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstronautFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('astronaut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Astronauts')),
            ],
        ),
        migrations.AlterField(
            model_name='orbiterflight',
            name='landing_crew',
            field=models.ManyToManyField(blank=True, related_name='landing_crew', to='api.AstronautFlight'),
        ),
        migrations.AlterField(
            model_name='orbiterflight',
            name='launch_crew',
            field=models.ManyToManyField(blank=True, related_name='launch_crew', to='api.AstronautFlight'),
        ),
        migrations.AlterField(
            model_name='orbiterflight',
            name='onboard_crew',
            field=models.ManyToManyField(blank=True, related_name='onboard_crew', to='api.AstronautFlight'),
        ),
    ]
