# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 00:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_full_name(apps, schema_editor):
    LauncherDetail = apps.get_model("api", "LauncherDetail")
    for launcher in LauncherDetail.objects.all():
        launcher.full_name = launcher.name + " " + launcher.variant
        launcher.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20171213_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcherdetail',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.RunPython(add_full_name),
        migrations.AlterField(
            model_name='launcherdetail',
            name='launch_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launcher_list', to='api.Agency'),
        ),
        migrations.AlterField(
            model_name='orbiter',
            name='launch_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orbiter_list', to='api.Agency'),
        ),
    ]
