# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 02:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181205_1651'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orbiter',
            new_name='Spacecraft',
        ),
        migrations.AlterModelOptions(
            name='spacecraft',
            options={'verbose_name': 'Spacecraft', 'verbose_name_plural': 'Spacecrafts'},
        ),
    ]
