# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-23 19:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20171220_0005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Launcher',
        ),
    ]
