# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181205_0221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrbiterFlight',
            new_name='SpacecraftFlight',
        ),
    ]
