# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_delete_launcher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['agency'], 'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='launcherdetail',
            options={'ordering': ['name'], 'verbose_name': 'Launcher Detail', 'verbose_name_plural': 'Launcher Details'},
        ),
        migrations.AlterModelOptions(
            name='orbiter',
            options={'ordering': ['name'], 'verbose_name': 'Orbiter', 'verbose_name_plural': 'Orbiters'},
        ),
        migrations.AddField(
            model_name='agency',
            name='ceo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agency',
            name='founding_year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agency',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
