# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-04 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181204_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launch_library_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='launch',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
