# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-04 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20181204_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launch',
            old_name='new_id',
            new_name='id',
        ),
    ]
