# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20180425_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='logo',
        ),
        migrations.AddField(
            model_name='agency',
            name='logo_url',
            field=models.URLField(blank=True),
        ),
    ]
