# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180425_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='launch_library_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
