# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_agency_launch_library_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
