# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_agency_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='launch_library_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
