# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-25 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180425_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
