# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-04 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def create_ids(apps, schema_editor):
    Launch = apps.get_model('api', 'Launch')
    for m in Launch.objects.all():
        m.new_id = uuid.uuid4()
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20181206_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.RunPython(code=create_ids),
        migrations.RenameField(
            model_name='launch',
            old_name='id',
            new_name='launch_library_id',
        ),
        migrations.AlterField(
            model_name='launch',
            name='launch_library_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='launch',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='launch',
            old_name='new_id',
            new_name='id',
        ),
    ]
