# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-04 22:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0020_launch_new_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launch',
            old_name='id',
            new_name='launch_library_id',
        ),
    ]
