# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_migrate_agency_primary_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'ordering': ['name'], 'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='agency',
            new_name='name',
        ),
    ]
