# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-08 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20181208_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
