# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20180426_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
