# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-04 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0023_launch_new_id_part4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launch',
            old_name='new_id',
            new_name='id',
        ),
    ]
