# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20180426_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=2048, null=True),
        ),
    ]
