# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-26 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180426_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='ceo',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
