# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-08 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20181207_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launch_library',
            field=models.NullBooleanField(default=False),
        ),
    ]
