# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-29 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180428_1733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='image_url',
            new_name='legacy_image_url',
        ),
        migrations.RenameField(
            model_name='launcherdetail',
            old_name='image_url',
            new_name='legacy_image_url',
        ),
        migrations.RenameField(
            model_name='orbiter',
            old_name='image_url',
            new_name='legacy_image_url',
        ),
    ]
