# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-27 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20180426_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='test',
            field=models.FileField(default=None, upload_to=b''),
        ),
    ]
