# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-30 00:27
from __future__ import unicode_literals

import api.models
import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180429_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='image_url',
            field=models.FileField(blank=True, default=None, null=True, storage=custom_storages.AgencyImageStorage(), upload_to=api.models.image_path),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='image_url',
            field=models.FileField(blank=True, default=None, null=True, storage=custom_storages.LauncherImageStorage(), upload_to=api.models.image_path),
        ),
        migrations.AddField(
            model_name='orbiter',
            name='image_url',
            field=models.FileField(blank=True, default=None, null=True, storage=custom_storages.OrbiterImageStorage(), upload_to=api.models.image_path),
        ),
    ]
