# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-28 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_agency_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='test',
            field=models.FileField(default=None, upload_to='spacelaunchnow.storage_backends.MediaStorage'),
        ),
    ]
