# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-30 01:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180430_0027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='nation_url',
            new_name='legacy_nation_url',
        ),
        migrations.RenameField(
            model_name='orbiter',
            old_name='nation_url',
            new_name='legacy_nation_url',
        ),
    ]
