# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-30 01:57
from __future__ import unicode_literals

import api.models
import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180430_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='nation_url',
            field=models.FileField(blank=True, default=None, null=True, storage=custom_storages.AgencyNationStorage(), upload_to=api.models.image_path),
        ),
        migrations.AddField(
            model_name='orbiter',
            name='nation_url',
            field=models.FileField(blank=True, default=None, null=True, storage=custom_storages.AgencyNationStorage(), upload_to=api.models.image_path),
        ),
    ]
