# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def rebuild_fk(apps, schema_editor):
    infourls = apps.get_model('api', 'infourls')
    vidurls = apps.get_model('api', 'vidurls')
    LaunchModel = apps.get_model('api', 'launch')
    for m in infourls.objects.all():
        launch = LaunchModel.objects.get(launch_library_id=m.launch_id_migration)
        m.launch = launch
        m.save()

    for m in vidurls.objects.all():
        launch = LaunchModel.objects.get(launch_library_id=m.launch_id_migration)
        m.launch = launch
        m.save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20181208_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='infourls',
            name='launch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_urls', to='api.Launch'),
        ),
        migrations.AddField(
            model_name='vidurls',
            name='launch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vid_urls', to='api.Launch'),
        ),
        migrations.RunPython(code=rebuild_fk),
        migrations.RemoveField(
            model_name='vidurls',
            name='launch_id_migration',
        ),
        migrations.RemoveField(
            model_name='infourls',
            name='launch_id_migration',
        ),
    ]
