# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-01 00:17
from __future__ import unicode_literals

import api.models
import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180430_0157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('location', models.CharField(blank=True, default='', max_length=100)),
                ('feature_image', models.FileField(blank=True, default=None, null=True, storage=custom_storages.EventImageStorage(), upload_to=api.models.image_path)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
