# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20181208_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infourls',
            name='launch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_urls', to='api.Launch'),
        ),
        migrations.AlterField(
            model_name='vidurls',
            name='launch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid_urls', to='api.Launch'),
        ),
    ]
