# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-02 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcherdetail',
            name='capability',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='launcherdetail',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orbiter',
            name='capability',
            field=models.CharField(default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='orbiter',
            name='in_use',
            field=models.BooleanField(default=True),
        ),
    ]
