# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-26 01:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20180601_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(default=datetime.tzinfo),
        ),
    ]
