# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20180705_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Info URL',
                'verbose_name_plural': 'Info URLs',
            },
        ),
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('img_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('netstamp', models.IntegerField(blank=True, null=True)),
                ('wsstamp', models.IntegerField(blank=True, null=True)),
                ('westamp', models.IntegerField(blank=True, null=True)),
                ('net', models.DateTimeField(max_length=255, null=True)),
                ('window_end', models.DateTimeField(max_length=255, null=True)),
                ('window_start', models.DateTimeField(max_length=255, null=True)),
                ('isostart', models.CharField(blank=True, max_length=255, null=True)),
                ('isoend', models.CharField(blank=True, max_length=255, null=True)),
                ('isonet', models.CharField(blank=True, max_length=255, null=True)),
                ('inhold', models.NullBooleanField(default=False)),
                ('tbdtime', models.NullBooleanField(default=False)),
                ('tbddate', models.NullBooleanField(default=False)),
                ('probability', models.IntegerField(blank=True, null=True)),
                ('holdreason', models.CharField(blank=True, max_length=255, null=True)),
                ('failreason', models.CharField(blank=True, max_length=255, null=True)),
                ('hashtag', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Launch',
                'verbose_name_plural': 'Launches',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('country_code', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='LSP',
            fields=[
                ('agency_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Agency')),
            ],
            options={
                'verbose_name': 'LSP',
                'verbose_name_plural': 'LSPs',
            },
            bases=('api.agency',),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('type_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
            },
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('agency_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('info_url', models.URLField(blank=True, null=True)),
                ('wiki_url', models.URLField(blank=True, null=True)),
                ('map_url', models.URLField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pad', to='api.Location')),
            ],
            options={
                'verbose_name': 'Pad',
                'verbose_name_plural': 'Pads',
            },
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imageURL', models.URLField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('configuration', models.CharField(blank=True, default='', max_length=255)),
                ('family_name', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Rocket',
                'verbose_name_plural': 'Rockets',
            },
        ),
        migrations.CreateModel(
            name='VidURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_url', models.URLField()),
                ('launch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid_urls', to='api.Launch')),
            ],
            options={
                'verbose_name': 'Video URL',
                'verbose_name_plural': 'Video URLs',
            },
        ),
        migrations.RemoveField(
            model_name='agency',
            name='launch_library_id',
        ),
        migrations.AddField(
            model_name='agency',
            name='abbrev',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agency',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agency',
            name='info_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='launch',
            name='lsp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.LSP'),
        ),
        migrations.AddField(
            model_name='launch',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Mission'),
        ),
        migrations.AddField(
            model_name='launch',
            name='pad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Pad'),
        ),
        migrations.AddField(
            model_name='launch',
            name='rocket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Rocket'),
        ),
        migrations.AddField(
            model_name='infourls',
            name='launch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_urls', to='api.Launch'),
        ),
    ]
