# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20181209_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
