# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models

def seed_field(apps, schema_editor):
    rocket = apps.get_model('api', 'rocket')
    for m in rocket.objects.all():
        if m.configuration is not None:
            m.config_id_migration = m.configuration.id
        m.save()

    launcher = apps.get_model('api', 'launcher')
    for m in launcher.objects.all():
        if m.launcher_config is not None:
            m.config_id_migration = m.launcher_config.id
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20181209_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='config_id_migration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launcher',
            name='config_id_migration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(code=seed_field),
    ]
