# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20180705_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
