# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_launcher_config_custom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rocket',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='launcher',
            name='launcher_config',
        ),
        migrations.RenameField(
            model_name='launcherconfig',
            old_name='id',
            new_name='launch_library_id',
        ),

    ]
