# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20180705_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='launcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Launcher'),
        ),
    ]
