# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models


def seed_field(apps, schema_editor):
    rocket = apps.get_model('api', 'rocket')
    for m in rocket.objects.all():
        if m.mission is not None:
            m.config_id_migration = m.rocket.id
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_launcher_config_custom_part2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcherconfig',
            name='launch_library_id',
            field=models.IntegerField(primary_key=False, unique=True),
        ),
    ]
