# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_launch_launcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launcher',
            name='s_family',
        ),
        migrations.RemoveField(
            model_name='launcher',
            name='vehicle_class',
        ),
        migrations.AlterField(
            model_name='launcher',
            name='apogee',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launcher',
            name='diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launcher',
            name='gto_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launcher',
            name='launch_mass',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launcher',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launcher',
            name='leo_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launcher',
            name='to_thrust',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='launcher',
            name='vehicle_range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
