# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 17:24
from __future__ import unicode_literals

from django.db import migrations, models


def rebuild_fk(apps, schema_editor):
    rocket = apps.get_model('api', 'rocket')
    for m in rocket.objects.all():
        if m.config_id_migration is not None:
            try:
                config = apps.get_model('api', 'launcherconfig')
                configObj = config.objects.get(launch_library_id=m.config_id_migration)
                if configObj is not None:
                    m.configuration = configObj
            except Exception as e:
                print("Config ID: %s ID: %s %s" % (m.config_id_migration, m.id, e))
        m.save()

    launcher = apps.get_model('api', 'launcher')
    for m in launcher.objects.all():
        if m.config_id_migration is not None:
            try:
                config = apps.get_model('api', 'launcherconfig')
                configObj = config.objects.get(launch_library_id=m.config_id_migration)
                if configObj is not None:
                    m.launcher_config = configObj
            except Exception as e:
                print("Config ID: %s ID: %s %s" % (m.config_id_migration, m.id, e))
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_launcher_config_custom_part3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcherconfig',
            name='launch_library_id',
            field=models.IntegerField(primary_key=False),
        ),
        migrations.AddField(
            model_name='launcherconfig',
            name='id',
            field=models.AutoField(primary_key=True)
        ),
        migrations.AddField(
            model_name='rocket',
            name='configuration',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE,
                                    null=True,
                                    to='api.LauncherConfig'),
        ),
        migrations.AddField(
            model_name='launcher',
            name='launcher_config',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE,
                                    null=True,
                                    to='api.LauncherConfig'),
        ),
        migrations.RunPython(code=rebuild_fk),
        migrations.RemoveField(
            model_name='rocket',
            name='config_id_migration',
        ),
        migrations.RemoveField(
            model_name='launcher',
            name='config_id_migration',
        ),
    ]
