# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20180706_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='status_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
