# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_launch_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='lsp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Agency'),
        ),
        migrations.DeleteModel(
            name='LSP',
        ),
    ]
