# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20181209_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='launcherconfig',
            options={'ordering': ['name'], 'verbose_name': 'Launcher Configuration', 'verbose_name_plural': 'Launcher Configurations'},
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='launch_library_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
