# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 18:33
from __future__ import unicode_literals

from django.db import migrations, models


def seed_field(apps, schema_editor):
    launch = apps.get_model('api', 'launch')
    for m in launch.objects.all():
        if m.pad is not None:
            m.pad_id_migration = m.pad.id
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20181209_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='pad_id_migration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(code=seed_field),
        migrations.RemoveField(
            model_name='launch',
            name='pad',
        ),
        migrations.RenameField(
            model_name='pad',
            old_name='id',
            new_name='launch_library_id',
        ),
    ]
