# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-07 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20180706_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcher',
            name='info_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='launcher',
            name='wiki_url',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
