# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_pad_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pad',
            name='launch_library_id',
            field=models.IntegerField(primary_key=False, unique=True),
        ),
    ]
