# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-08 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20180707_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
