# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-08 17:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_launch_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='ceo',
            new_name='administrator',
        ),
    ]
