# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 18:33
from __future__ import unicode_literals

from django.db import migrations, models


def rebuild_fk(apps, schema_editor):
    launch = apps.get_model('api', 'launch')
    for m in launch.objects.all():
        if m.pad_id_migration is not None:
            try:
                pad = apps.get_model('api', 'pad')
                padObj = pad.objects.get(launch_library_id=m.pad_id_migration)
                if padObj is not None:
                    m.pad = padObj
            except Exception as e:
                print("Pad ID: %s ID: %s %s" % (m.pad_id_migration, m.id, e))
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_pad_custom_part3'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='pad',
            field=models.ForeignKey(null=True,
                                    on_delete=models.deletion.SET_NULL,
                                    related_name='launch',
                                    to='api.Pad')
        ),
        migrations.RunPython(code=rebuild_fk),
        migrations.RemoveField(
            model_name='launch',
            name='pad_id_migration',
        ),
    ]
