# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models


def seed_field(apps, schema_editor):
    pad = apps.get_model('api', 'pad')
    for m in pad.objects.all():
        if m.location is not None:
            m.location_id_migration = m.location.id
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_pad_custom_part4'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='location_id_migration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(code=seed_field),
        migrations.RemoveField(
            model_name='pad',
            name='location',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='id',
            new_name='launch_library_id',
        ),
    ]
