# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-10 05:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20180710_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 7, 10, 1, 12, 53, 693000)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='launch',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
