# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20180710_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcher',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
