# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_location_custom_part2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='launch_library_id',
            field=models.IntegerField(primary_key=False, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.AutoField(primary_key=True)
        ),
    ]
