# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_auto_20180710_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbiter',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
