# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models

def rebuild_fk(apps, schema_editor):
    pad = apps.get_model('api', 'pad')
    for m in pad.objects.all():
        if m.location_id_migration is not None:
            try:
                location = apps.get_model('api', 'location')
                locationObj = location.objects.get(launch_library_id=m.location_id_migration)
                if locationObj is not None:
                    m.location = locationObj
            except Exception as e:
                print("Location ID: %s ID: %s %s" % (m.location_id_migration, m.id, e))
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_location_custom_part3'),
    ]

    operations = [
        migrations.AddField(
            model_name='pad',
            name='location',
            field=models.ForeignKey(blank=True,
                                    null=True,
                                    on_delete=models.deletion.CASCADE,
                                    related_name='pad',
                                    to='api.Location')
        ),
        migrations.RunPython(code=rebuild_fk),
        migrations.RemoveField(
            model_name='pad',
            name='location_id_migration',
        ),
    ]
