# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-13 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_location_custom_part4'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockedVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docking', models.DateTimeField()),
                ('departure', models.DateTimeField(blank=True, null=True)),
                ('flight_vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.SpacecraftFlight')),
            ],
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('crew', models.ManyToManyField(related_name='expeditions', to='api.AstronautFlight')),
            ],
        ),
        migrations.RemoveField(
            model_name='spacestation',
            name='docked_vehicles',
        ),
        migrations.AddField(
            model_name='spacestation',
            name='expeditions',
            field=models.ManyToManyField(blank=True, null=True, to='api.Expedition'),
        ),
        migrations.AddField(
            model_name='spacestation',
            name='visiting_vehicles',
            field=models.ManyToManyField(blank=True, null=True, to='api.DockedVehicle'),
        ),
    ]
