# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-25 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20180710_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launcher',
            name='agency',
        ),
        migrations.AddField(
            model_name='pad',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pad',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
