# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-06 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20180725_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='launch_library',
            field=models.NullBooleanField(default=True),
        ),
    ]
