# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-21 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_auto_20181217_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spacestation',
            name='owner',
        ),
        migrations.AddField(
            model_name='spacestation',
            name='owners',
            field=models.ManyToManyField(to='api.Agency'),
        ),
    ]
