# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_launch_launch_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_agencies', to='api.Agency'),
        ),
    ]
