# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 19:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_agency_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('type_name', models.CharField(blank=True, default='', max_length=255)),
                ('agencies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payload', to='api.Agency')),
            ],
        ),
    ]
