# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-20 19:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_auto_20180819_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='launcher',
            options={'ordering': ['name'], 'verbose_name': 'Launcher Configurations', 'verbose_name_plural': 'Launcher Configurations'},
        ),
        migrations.AlterModelOptions(
            name='orbiter',
            options={'ordering': ['name'], 'verbose_name': 'Spacecraft', 'verbose_name_plural': 'Spacecrafts'},
        ),
    ]
