# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20180820_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='LauncherInstance',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(blank=True, max_length=10, null=True)),
                ('flight_number', models.IntegerField(blank=True, null=True)),
                ('reused', models.BooleanField(default=False)),
                ('land_success', models.NullBooleanField()),
                ('landing_type', models.CharField(blank=True, max_length=10, null=True)),
                ('landing_vehicle', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'ordering': ['serial_number'],
                'verbose_name': 'Launcher',
                'verbose_name_plural': 'Launchers',
            },
        ),
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('abbrev', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Orbit',
                'verbose_name_plural': 'Orbits',
            },
        ),
        migrations.CreateModel(
            name='Payload',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=2048)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('type_name', models.CharField(blank=True, default='', max_length=255)),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='api.Mission')),
            ],
        ),
        migrations.RenameModel(
            old_name='Launcher',
            new_name='LauncherConfig',
        ),
        migrations.RenameField(
            model_name='launch',
            old_name='launcher',
            new_name='launcher_config',
        ),
        migrations.AddField(
            model_name='agency',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_agencies', to='api.Agency'),
        ),
        migrations.AddField(
            model_name='launcherinstance',
            name='launcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launcher', to='api.LauncherConfig'),
        ),
        migrations.AddField(
            model_name='launch',
            name='orbit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Orbit'),
        ),
    ]
