# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-16 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='payload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='api.Payload'),
        ),
    ]
