# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 22:29
from __future__ import unicode_literals

import api.models
import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_auto_20190105_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacestation',
            name='image_url',
            field=models.FileField(blank=True, default=None, null=True, storage=custom_storages.SpaceStationImageStorage(), upload_to=api.models.image_path),
        ),
        migrations.AlterField(
            model_name='spacestation',
            name='active_expeditions',
            field=models.ManyToManyField(blank=True, to='api.Expedition'),
        ),
    ]
