# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-17 02:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_mission_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='payload',
        ),
        migrations.RemoveField(
            model_name='payload',
            name='agencies',
        ),
        migrations.AddField(
            model_name='payload',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payloads', to='api.Mission'),
        ),
    ]
