# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 21:25
from __future__ import unicode_literals

import api.models
import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20190110_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='image_url',
            field=models.FileField(blank=True, default=None, null=True, storage=custom_storages.LauncherCoreImageStorage(), upload_to=api.models.image_path),
        ),
    ]
