# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-20 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_launcher_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spacecraftconfiguration',
            name='maiden_flight',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
