# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_auto_20180816_2249'),
        ('api', '0053_auto_20180819_0023'),
    ]

    operations = [
    ]
