# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_merge_20180819_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orbit',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('abbrev', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Orbit',
                'verbose_name_plural': 'Orbits',
            },
        ),
        migrations.RenameModel(
            old_name='Launcher',
            new_name='LauncherConfig',
        ),
        migrations.AlterModelOptions(
            name='launcherconfig',
            options={'ordering': ['name'], 'verbose_name': 'Launcher Configurations', 'verbose_name_plural': 'Launcher Configurations'},
        ),
        migrations.AlterModelOptions(
            name='orbiter',
            options={'ordering': ['name'], 'verbose_name': 'Spacecraft', 'verbose_name_plural': 'Spacecrafts'},
        ),
        migrations.AddField(
            model_name='launch',
            name='orbit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Orbit'),
        ),
    ]
