# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_auto_20180821_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='launcher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Launcher'),
        ),
    ]
