# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_launch_launcher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='orbit',
        ),
        migrations.AddField(
            model_name='mission',
            name='orbit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='api.Orbit'),
        ),
    ]
