# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-19 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_auto_20180819_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launch',
            old_name='launcher',
            new_name='launcher_config',
        ),
    ]
