# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-20 18:43
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_astronauttype'),
        ('api', '0059_auto_20190120_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronaut',
            name='type',
            field=models.ForeignKey(default=api.models.get_default_astronaut_config_type,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='configurations.AstronautType'),
        ),

    ]
