# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_auto_20180821_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='orbit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='api.Orbit'),
        ),
    ]
