# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-20 18:43
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion


def fix_status(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    AstronautType = apps.get_model("configurations", "AstronautType")
    AstronautType.objects.using(db_alias).create(id=2, name="Government")
    AstronautType.objects.using(db_alias).create(id=3, name="Private")

    Astronaut = apps.get_model('api', 'Astronaut')
    for astronaut in Astronaut.objects.all():
        if astronaut.status.id <= 8:
            astronaut.type = AstronautType.objects.get(id=2)
        else:
            astronaut.type = AstronautType.objects.get(id=3)
        astronaut.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_astronaut_type'),
    ]

    operations = [
        migrations.RunPython(fix_status),
    ]
