# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20180821_1514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launcher',
            old_name='launcher',
            new_name='launcher_config',
        ),
    ]
