# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_astronaut_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacestation',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height (m)'),
        ),
        migrations.AddField(
            model_name='spacestation',
            name='mass',
            field=models.FloatField(blank=True, null=True, verbose_name='Mass (T)'),
        ),
        migrations.AddField(
            model_name='spacestation',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Volume (m^3)'),
        ),
        migrations.AddField(
            model_name='spacestation',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Width (m)'),
        ),
    ]
