# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_auto_20180821_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launcher',
            name='flight_number',
        ),
        migrations.RemoveField(
            model_name='launcher',
            name='land_success',
        ),
        migrations.RemoveField(
            model_name='launcher',
            name='landing_type',
        ),
        migrations.RemoveField(
            model_name='launcher',
            name='landing_vehicle',
        ),
        migrations.RemoveField(
            model_name='launcher',
            name='reused',
        ),
        migrations.AddField(
            model_name='launch',
            name='land_success',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='launch',
            name='landing_location',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='landing_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='reused',
            field=models.BooleanField(default=False),
        ),
    ]
