# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-21 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20180821_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='api.MissionType'),
        ),
    ]
