# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-22 22:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0012_spacestationtype'),
        ('api', '0062_auto_20190122_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacestation',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='configurations.SpaceStationType'),
        ),
    ]
