# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_spacestation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spacestation',
            name='deorbited',
            field=models.DateField(blank=True, null=True),
        ),
    ]
