# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-25 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_spacestation_deorbited'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockingevent',
            name='docked',
            field=models.BooleanField(default=False),
        ),
    ]
