# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-22 03:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_auto_20180821_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchStatus',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='launch',
            name='launch_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.LaunchStatus'),
        ),
    ]
