# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-31 21:29
from __future__ import unicode_literals

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0013_eventtype'),
        ('api', '0065_dockingevent_docked'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='news_url',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='type',
            field=models.ForeignKey(default=api.models.get_default_event_config_type, on_delete=django.db.models.deletion.CASCADE, to='configurations.EventType'),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
