# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-24 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_auto_20180821_2336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='launchstatus',
            options={'verbose_name': 'Launch Status', 'verbose_name_plural': 'Launch Statuses'},
        ),
        migrations.RemoveField(
            model_name='launch',
            name='launcher',
        ),
        migrations.AddField(
            model_name='launch',
            name='launcher',
            field=models.ManyToManyField(to='api.Launcher'),
        ),
    ]
