# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-27 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20180823_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcherconfig',
            name='geo_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launcherconfig',
            name='launch_cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='launcherconfig',
            name='sso_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
