# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 21:28
from __future__ import unicode_literals

import api.models
import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20190227_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launcher',
            name='image_url',
            field=models.FileField(blank=True, default=None, null=True, storage=custom_storages.LauncherCoreImageStorage(), upload_to=api.models.launcher_path),
        ),
    ]
