# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-27 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20180827_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agency', to='configurations.AgencyType'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='landing_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='configurations.LandingLocation'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='landing_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='configurations.LandingType'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='launch_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='configurations.LaunchStatus'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='mission_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='configurations.MissionType'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='orbit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission', to='configurations.Orbit'),
        ),
        migrations.DeleteModel(
            name='AgencyType',
        ),
        migrations.DeleteModel(
            name='LandingLocation',
        ),
        migrations.DeleteModel(
            name='LandingType',
        ),
        migrations.DeleteModel(
            name='LaunchStatus',
        ),
        migrations.DeleteModel(
            name='MissionType',
        ),
        migrations.DeleteModel(
            name='Orbit',
        ),
    ]
