# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_auto_20190304_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='notifications_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='was_discorded_ten_minutes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='was_discorded_webcast_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='was_notified_ten_minutes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='was_notified_webcast_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='was_tweeted_ten_minutes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='was_tweeted_webcast_live',
            field=models.BooleanField(default=False),
        ),
    ]
