# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20180827_1755'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='launcher',
            options={'ordering': ['serial_number'], 'verbose_name': 'Launch Vehicle', 'verbose_name_plural': 'Launcher Vehicles'},
        ),
        migrations.RemoveField(
            model_name='launch',
            name='reused',
        ),
        migrations.AddField(
            model_name='launcher',
            name='flight_proven',
            field=models.BooleanField(default=False),
        ),
    ]
