# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-24 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20190306_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='api.Mission'),
        ),
    ]
