# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-27 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20180827_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcher',
            name='details',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='launcher',
            name='status',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
