# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-26 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20190324_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='webcast_live',
            field=models.BooleanField(default=False),
        ),
    ]
