# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-17 13:59
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_launch_webcast_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name', 'id']),
        ),
    ]
