# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-18 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_events_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='img_url',
        ),
    ]
