# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-01 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_auto_20180830_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='landing_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='configurations.LandingLocation'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='landing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='configurations.LandingType'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='launcher',
            field=models.ManyToManyField(blank=True, null=True, related_name='launch', to='api.Launcher'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='launcher_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.LauncherConfig'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='lsp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Agency'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='apogee',
            field=models.IntegerField(blank=True, null=True, verbose_name='Apogee - Sub-Orbital Only (km)'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='diameter',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Diameter (m)'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='fairing_diameter',
            field=models.FloatField(blank=True, null=True, verbose_name='Max Fairing Diameter (m)'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='geo_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='GEO Capacity (kg)'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='gto_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='GTO Capacity (kg)'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='launch_cost',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Launch Cost ($)'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='launch_mass',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mass at Launch (kg)'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='length',
            field=models.FloatField(blank=True, null=True, verbose_name='Length (m)'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='leo_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='LEO Capacity (kg)'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='to_thrust',
            field=models.IntegerField(blank=True, null=True, verbose_name='Thrust at Liftoff (kN)'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='vehicle_range',
            field=models.IntegerField(blank=True, null=True, verbose_name='Vehicle Range - Legacy'),
        ),
    ]
