# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_auto_20180827_2000'),
        ('api', '0074_auto_20180831_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.NullBooleanField(default=False)),
                ('success', models.NullBooleanField()),
                ('landing_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='configurations.LandingLocation')),
                ('landing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='configurations.LandingType')),
            ],
        ),
        migrations.RemoveField(
            model_name='launch',
            name='land_success',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='landing_location',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='landing_type',
        ),
        migrations.AddField(
            model_name='launch',
            name='landing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Landing'),
        ),
    ]
