# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 19:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_auto_20180905_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='landing_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing', to='configurations.LandingLocation'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='landing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landing', to='configurations.LandingType'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='landing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Landing'),
        ),
    ]
