# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20180905_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landing',
            old_name='attempted',
            new_name='attempt',
        ),
    ]
