# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_auto_20180905_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='landing',
            name='description',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
