# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_landing_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='landing_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing', to='configurations.LandingLocation'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='landing_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing', to='configurations.LandingType'),
        ),
    ]
