# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-29 21:01
from __future__ import unicode_literals

import api.models
import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_pad_map_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launcherconfig',
            old_name='launch_agency',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='spacecraftconfiguration',
            old_name='launch_agency',
            new_name='manufacturer',
        ),
        migrations.AlterField(
            model_name='pad',
            name='map_image',
            field=models.FileField(blank=True, default=None, null=True, storage=custom_storages.LaunchImageStorage(), upload_to=api.models.pad_path),
        ),
    ]
