# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_auto_20180905_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='landing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='api.Landing'),
        ),
    ]
