# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-05 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_auto_20180905_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launcher_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='api.LauncherConfig'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='lsp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='api.Agency'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='api.Mission'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='pad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='api.Pad'),
        ),
    ]
