# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-10 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20180905_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orbiter',
            name='legacy_image_url',
        ),
        migrations.RemoveField(
            model_name='orbiter',
            name='legacy_nation_url',
        ),
        migrations.AddField(
            model_name='orbiter',
            name='crew_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Crew Capacity'),
        ),
        migrations.AddField(
            model_name='orbiter',
            name='diameter',
            field=models.FloatField(blank=True, null=True, verbose_name='Diameter (m)'),
        ),
        migrations.AddField(
            model_name='orbiter',
            name='flight_life',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='orbiter',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Length (m)'),
        ),
        migrations.AddField(
            model_name='orbiter',
            name='info_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='orbiter',
            name='maiden_flight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orbiter',
            name='payload_capacity',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
