# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-14 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20190730_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
