# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-11 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_auto_20190730_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='launch_library_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['name']),
        ),
    ]
