# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-28 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_events_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='launch',
            name='launch_service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Agency', verbose_name='Launch Service Provider'),
        ),
    ]
