# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-10 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_auto_20180910_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbiter',
            name='maiden_flight',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
