# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-12-17 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_auto_20190928_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
