# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-27 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20191217_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='infourls',
            name='customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vidurls',
            name='customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='infourls',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='infourls',
            name='feature_image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='infourls',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='infourls',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vidurls',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='vidurls',
            name='feature_image',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='vidurls',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vidurls',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
