# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-10 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0084_auto_20180910_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orbiter',
            name='payload_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Payload Capacity (kg)'),
        ),
    ]
