# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-04 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20200127_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infourls',
            options={'ordering': ['priority'], 'verbose_name': 'Info URL', 'verbose_name_plural': 'Info URLs'},
        ),
        migrations.AlterModelOptions(
            name='vidurls',
            options={'ordering': ['priority'], 'verbose_name': 'Video URL', 'verbose_name_plural': 'Video URLs'},
        ),
        migrations.AddField(
            model_name='launch',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
