# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-14 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_auto_20180910_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firststage', to='api.Landing')),
                ('launcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firststage', to='api.Launcher')),
            ],
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SecondStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondstage', to='api.Landing')),
                ('launcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondstage', to='api.Launcher')),
                ('rocket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondstage', to='api.Rocket')),
            ],
        ),
        migrations.RemoveField(
            model_name='launch',
            name='landing',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='launcher',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='launcher_config',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='lsp',
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='launch_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launcher_config', to='api.Agency'),
        ),
        migrations.AddField(
            model_name='rocket',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rocket', to='api.LauncherConfig'),
        ),
        migrations.AddField(
            model_name='firststage',
            name='rocket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firststage', to='api.Rocket'),
        ),
        migrations.AddField(
            model_name='launch',
            name='rocket',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='api.Rocket'),
        ),
    ]
