# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-02-04 19:41
from __future__ import unicode_literals

import api.models
import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_auto_20200204_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='feature_image',
            field=models.FileField(default='default.png', storage=custom_storages.EventImageStorage(), upload_to=api.models.image_path),
        ),
    ]
