# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20180915_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='rocket',
            name='reused',
            field=models.NullBooleanField(),
        ),
    ]
