# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-17 15:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_auto_20180915_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='status',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='status_name',
        ),
    ]
