# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-17 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_auto_20180827_2000'),
        ('api', '0088_auto_20180917_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='launch_status',
        ),
        migrations.AddField(
            model_name='launch',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='configurations.LaunchStatus'),
        ),
    ]
