# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0088_auto_20180917_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='launch_status',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='status_name',
        ),
        migrations.AddField(
            model_name='rocket',
            name='reused',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='launch',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='launch', to='configurations.LaunchStatus'),
        ),
        migrations.AlterField(
            model_name='launcherconfig',
            name='launch_agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launcher_list', to='api.Agency'),
        ),
    ]
