# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_firststagetype'),
        ('api', '0089_auto_20180919_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='firststage',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firststage', to='configurations.FirstStageType'),
        ),
    ]
