# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_firststage_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rocket',
            name='reused',
        ),
        migrations.AddField(
            model_name='firststage',
            name='reused',
            field=models.NullBooleanField(),
        ),
    ]
