# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-30 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_auto_20180919_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='launcherconfig',
            name='maiden_flight',
            field=models.DateField(blank=True, max_length=255, null=True, verbose_name='Maiden Flight Date'),
        ),
    ]
