version: '3'
services:
 web:
   build: ../../..
   command: bash -c "python /code/manage.py runserver 0.0.0.0:8000"
   stdin_open: true
   tty: true
   volumes:
   - .:/code
   ports:
   - "8000:8000"