# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-26 18:10
from __future__ import unicode_literals

import app.models
import custom_storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navigation_drawer_image', models.FileField(blank=True, default=None, null=True, storage=custom_storages.AppImageStorage(), upload_to=app.models.image_path)),
            ],
            options={
                'verbose_name': 'Android App Config',
                'verbose_name_plural': 'Android App Config',
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
