# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-01 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='bio',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
