# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 17:25
from __future__ import unicode_literals

import app.models
import custom_storages
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('flag', models.FileField(storage=custom_storages.AppImageStorage(), upload_to=app.models.language_image_path)),
            ],
        ),
        migrations.AddField(
            model_name='translator',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language', to='app.Translator'),
        ),
    ]
