# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-27 17:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181027_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='translator',
        ),
        migrations.AddField(
            model_name='translator',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translator', to='app.Language'),
        ),
    ]
