version: '3'

services:
  discord-bot:
    container_name: discord-bot
    image: registry.calebjones.dev:5050/sln-server:production
    command: bash -c "python /code/bot.py"
    restart: always
    volumes:
      - ./log:/code/log
    labels:
      - "io.portainer.accesscontrol.teams=Space Launch Now"
