apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sln-infrastructure
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: spacelaunchnow
  source:
    repoURL: https://github.com/TheSpaceDevs/SpaceLaunchNow-Server
    targetRevision: HEAD
    path: manifests/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
