# Generated by Django 3.0.11 on 2021-10-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_auto_20210330_0038"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlenotification",
            name="sent_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
