# Generated by Django 4.2.6 on 2023-10-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_articlenotification_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='send_android_complete',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_ios_complete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
