services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  test:
    build:
      context: ../
      args:
        - PRIVATE_USERNAME=${POETRY_HTTP_BASIC_TSD_USERNAME}
        - PRIVATE_PASSWORD=${POETRY_HTTP_BASIC_TSD_PASSWORD}
    image: space_launch_now_local
    command: >
      bash -c "coverage run --data-file=/code/coverage/.coverage manage.py test --settings=spacelaunchnow.settings.test
      && coverage html --data-file=/code/coverage/.coverage
      && coverage report --data-file=/code/coverage/.coverage"
    volumes:
      - ../report/coverage/:/code/coverage/
      - ../report/htmlcov/:/code/htmlcov/
      - ../report/xmlrunner/:/code/xmlrunner/
    environment:
      - DEBUG=true
      - DJANGO_SECRET_KEY=${POETRY_HTTP_BASIC_TSD_PASSWORD}
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - USE_LOCAL_STORAGE=true
    depends_on:
      - db