version: '3'

services:
  web:
    build:
      context: ../
    image: space_launch_now_web
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    env_file:
      - .env