# External Secret for Monitoring Basic Auth
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-basic-auth
  namespace: monitoring
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: basic-auth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        auth: "{{ .auth }}"
  data:
  - secretKey: auth
    remoteRef:
      key: monitoring
      property: basic-auth-htpasswd
