# Default values for django.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: registry.digitalocean.com/spacelaunchnow-registry/space-launch-now-base
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

env:
  normal:
    DEBUG: "False"
    DATABASE_ENGINE: "django.db.backends.postgresql_psycopg2"
    DATABASE_NAME: "spacelaunchnow_prod_01"
    CACHE_BACKEND: "django.core.cache.backends.memcached.PyMemcacheCache"
    CACHE_LOCATION: "sln-prod-memcache-memcached.sln-prod.svc.cluster.local:11211"
    DISABLE_THROTTLE: "False"
    STORAGE_BUCKET_NAME: "spacelaunchnow-prod-east"
    AWS_S3_ENDPOINT_URL: "https://nyc3.digitaloceanspaces.com"
    EMAIL_HOST: "smtp.gmail.com"
    EMAIL_PORT: "587"
    EMAIL_HOST_TLS: "True"

  worker:
    IS_WEBSERVER: "False"
    IS_API: "False"
    IS_ADMIN: "False"

  web:
    IS_WEBSERVER: "True"
    IS_API: "True"
    IS_ADMIN: "True"

  service:
    IS_WEBSERVER: "False"
    IS_API: "False"
    IS_ADMIN: "False"

  secret: {}

web:
  replicaCount: 1
  port: 8080
  autoscaling:
    enabled: true
    minReplicas: 10
    maxReplicas: 40
    targetCPUUtilizationPercentage: 80
#    targetMemoryUtilizationPercentage: 80

  budget:
    minAvailable: 1 # Ignored when replicaCount is 1
  resources:
    limits:
      cpu: 250m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 350Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
    # podAntiAffinity:
    #   preferredDuringSchedulingIgnoredDuringExecution:
    #   - weight: 100
    #     podAffinityTerm:
    #       labelSelector:
    #         matchExpressions:
    #         - key: app.kubernetes.io/instance
    #           operator: In
    #           values:
    #           - glitchtip-prod-web
    #       topologyKey: kubernetes.io/hostname
  livenessProbe:
    failureThreshold: 10
    initialDelaySeconds: 5
    timeoutSeconds: 2
    path: "/_health/"
  readinessProbe:
    failureThreshold: 10
    initialDelaySeconds: 5
    timeoutSeconds: 2
    path: "/_health/"
  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    className: ""
    annotations:
     kubernetes.io/ingress.class: nginx
     cert-manager.io/cluster-issuer: letsencrypt-production
     nginx.ingress.kubernetes.io/proxy-body-size: 25m
     nginx.ingress.kubernetes.io/proxy-buffering: "on"
     nginx.ingress.kubernetes.io/configuration-snippet: |
       proxy_cache static-cache;
       proxy_cache_key $scheme$host$request_uri;
       proxy_cache_valid 429 10m;
       proxy_cache_valid any 1m;
       add_header X-Cache-Status $upstream_cache_status;
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: api.spacelaunchnow.me
        paths:
          - path: /
            pathType: ImplementationSpecific
      - host: spacelaunchnow.me
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: spacelaunchnow-tls
        hosts:
          - api.spacelaunchnow.me
          - spacelaunchnow.me

notification_service:
  enabled: true
  resources:
    limits:
      cpu: 900m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 128Mi

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

jobs:
  - name: sln-news-sync
    image:
      repository: registry.digitalocean.com/spacelaunchnow-registry/space-launch-now-base
      tag: latest
      imagePullPolicy: Always
    schedule: "*/5 * * * *"
    command: "['python', 'manage.py', 'run_get_news']"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 5
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
  - name: sln-news-deep-sync
    image:
      repository: registry.digitalocean.com/spacelaunchnow-registry/space-launch-now-base
      tag: latest
      imagePullPolicy: Always
    schedule: "0 */12 * * *"
    command: "['python', 'manage.py', 'run_get_news', '--limit', '50']"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 5
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
  - name: sln-autoscaler
    image:
      repository: registry.digitalocean.com/spacelaunchnow-registry/space-launch-now-base
      tag: latest
      imagePullPolicy: Always
    schedule: "*/7 * * * *"
    command: "['python', 'manage.py', 'check_autoscaler']"
    failedJobsHistoryLimit: 1
    successfulJobsHistoryLimit: 5
    concurrencyPolicy: Forbid
    restartPolicy: OnFailure
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    env:
    - name: DO_CLUSTER_ID
      valueFrom:
        secretKeyRef:
          name:  do-cluster-id
          key:  do-cluster-id
    - name: DO_TOKEN
      valueFrom:
        secretKeyRef:
          name: sln-auth-prod
          key: do-token