# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDigestRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('messages', models.TextField(blank=True, max_length=1048, null=True)),
                ('count', models.IntegerField(null=True)),
                ('data', models.TextField(blank=True, max_length=4096, null=True)),
            ],
            options={
                'verbose_name': 'Daily Digest - Record',
                'verbose_name_plural': 'Daily Digest - Records',
            },
        ),
        migrations.CreateModel(
            name='DiscordChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=4000, unique=True)),
                ('server_id', models.CharField(max_length=4000)),
                ('name', models.CharField(max_length=4000)),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('featured_image', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('news_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsNotificationChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=4000, unique=True)),
                ('server_id', models.CharField(max_length=4000)),
                ('name', models.CharField(max_length=4000)),
                ('subscribed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'News Notification Channel',
                'verbose_name_plural': 'News Notification Channels',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasNotifiedTwentyFourHour', models.BooleanField(default=False)),
                ('wasNotifiedOneHour', models.BooleanField(default=False)),
                ('wasNotifiedTenMinutes', models.BooleanField(default=False)),
                ('wasNotifiedOneMinute', models.BooleanField(default=False)),
                ('wasNotifiedInFlight', models.BooleanField(default=False)),
                ('wasNotifiedSuccess', models.BooleanField(default=False)),
                ('wasNotifiedTwentyFourHourTwitter', models.BooleanField(default=False)),
                ('wasNotifiedOneHourTwitter', models.BooleanField(default=False)),
                ('wasNotifiedTenMinutesTwitter', models.BooleanField(default=False)),
                ('wasNotifiedOneMinuteTwitter', models.BooleanField(default=False)),
                ('wasNotifiedInFlightTwitter', models.BooleanField(default=False)),
                ('wasNotifiedSuccessTwitter', models.BooleanField(default=False)),
                ('wasNotifiedDailyDigest', models.BooleanField(default=False)),
                ('last_twitter_post', models.DateTimeField(blank=True, null=True)),
                ('last_notification_sent', models.DateTimeField(blank=True, null=True)),
                ('last_notification_recipient_count', models.IntegerField(blank=True, null=True)),
                ('last_net_stamp', models.DateTimeField(blank=True, null=True)),
                ('last_net_stamp_timestamp', models.DateTimeField(blank=True, null=True)),
                ('wasNotifiedTwentyFourHourDiscord', models.BooleanField(default=False)),
                ('wasNotifiedOneHourDiscord', models.BooleanField(default=False)),
                ('wasNotifiedTenMinutesDiscord', models.BooleanField(default=False)),
                ('wasNotifiedOneMinutesDiscord', models.BooleanField(default=False)),
                ('wasNotifiedInFlightDiscord', models.BooleanField(default=False)),
                ('wasNotifiedSuccessDiscord', models.BooleanField(default=False)),
                ('launch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Launch')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='RedditSubmission',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('selftext', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('text', models.CharField(blank=True, default='', max_length=40000, null=True)),
                ('link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('permalink', models.CharField(max_length=255)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('initialized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubredditNotificationChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=4000, unique=True)),
                ('server_id', models.CharField(max_length=4000)),
                ('name', models.CharField(max_length=4000)),
            ],
            options={
                'verbose_name': 'Reddit Notification Channel',
                'verbose_name_plural': 'Reddit Notification Channels',
            },
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterNotificationChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=4000, unique=True)),
                ('server_id', models.CharField(max_length=4000)),
                ('name', models.CharField(max_length=4000)),
                ('default_subscribed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Twitter Notification Channel',
                'verbose_name_plural': 'Twitter Notification Channels',
            },
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('screen_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('profile_image', models.CharField(max_length=50)),
                ('custom', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
                ('subscribers', models.ManyToManyField(to='bot.TwitterNotificationChannel')),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tweets', to='bot.TwitterUser'),
        ),
        migrations.AddField(
            model_name='subreddit',
            name='subscribers',
            field=models.ManyToManyField(to='bot.SubredditNotificationChannel'),
        ),
        migrations.AddField(
            model_name='redditsubmission',
            name='subreddit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='bot.Subreddit'),
        ),
    ]
