# Generated by Django 3.0.11 on 2021-01-14 14:56

from django.db import migrations, models
import django.db.models.deletion


def delete_linked_models(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    ArticleNotification = apps.get_model('bot', 'ArticleNotification')
    ArticleNotification.objects.all().delete()
    Notification = apps.get_model('bot', 'Notification')
    Notification.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reset_fields'),
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(delete_linked_models),
        migrations.CreateModel(
            name='SNAPIArticle',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1048)),
                ('link', models.CharField(blank=True, default='', max_length=1048, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=40000, null=True)),
                ('featured_image', models.CharField(blank=True, default='', max_length=1048, null=True)),
                ('news_site', models.CharField(blank=True, default='', max_length=1048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('events', models.ManyToManyField(blank=True, related_name='snapi_articles', to='api.Events')),
                ('launches', models.ManyToManyField(blank=True, related_name='snapi_articles', to='api.Launch')),
            ],
        ),
        migrations.AlterField(
            model_name='articlenotification',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bot.SNAPIArticle'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='news',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapi_articles', to='bot.SNAPIArticle'),
        ),
    ]
