# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-29 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='last_daily_digest_post',
            new_name='last_daily_digest_analysis',
        ),
    ]
