# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20181106_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.CharField(max_length=1048),
        ),
    ]
