# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 03:52
from __future__ import unicode_literals

from django.db import migrations, models


def seed_field(apps, schema_editor):
    notification = apps.get_model('bot', 'notification')
    for m in notification.objects.all():
        m.launch_id_migration = m.launch.id
        m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20181106_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='launch_id_migration',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(code=seed_field),
        migrations.RemoveField(
            model_name='notification',
            name='launch',
        ),
    ]
