# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-05 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_add_digest_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydigestrecord',
            name='data',
            field=models.TextField(blank=True, max_length=4096, null=True),
        ),
    ]
