# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-09 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_notification_launch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='launch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Launch'),
        ),
    ]
