# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-26 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_auto_20181209_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedWebcastDiscord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedWebcastLive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedWebcastLiveTwitter',
            field=models.BooleanField(default=False),
        ),
    ]
