# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-12 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20171012_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vidurls',
            name='launch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vid_urls', to='bot.Launch'),
        ),
        migrations.AlterField(
            model_name='vidurls',
            name='vid_url',
            field=models.URLField(),
        ),
    ]
