# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-28 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_auto_20190426_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='should_notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='was_notified',
            field=models.BooleanField(default=False),
        ),
    ]
