# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-30 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_auto_20171012_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='launch',
            name='lsp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='lsp_name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
    ]
