# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-06 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_auto_20171030_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=b'', max_length=255)),
                ('country_code', models.CharField(blank=True, default=b'', max_length=255)),
                ('abbrev', models.CharField(blank=True, default=b'', max_length=255)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('info_url', models.URLField(blank=True)),
                ('wiki_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=b'', max_length=255)),
                ('country_code', models.CharField(blank=True, default=b'', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=b'', max_length=255)),
                ('description', models.CharField(blank=True, default=b'', max_length=2048)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('type_name', models.CharField(blank=True, default=b'', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=b'', max_length=255)),
                ('info_url', models.URLField(blank=True)),
                ('wiki_url', models.URLField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('location', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Rocket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imageURL', models.URLField()),
                ('name', models.CharField(blank=True, default=b'', max_length=255)),
                ('configuration', models.CharField(blank=True, default=b'', max_length=255)),
                ('family_name', models.CharField(blank=True, default=b'', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='launch',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='lsp_id',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='lsp_name',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='mission_description',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='mission_name',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='mission_type',
        ),
        migrations.RemoveField(
            model_name='launch',
            name='rocket_name',
        ),
        migrations.AlterField(
            model_name='launch',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='launch',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LSP',
            fields=[
                ('agency_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.Agency')),
                ('launches', models.ManyToManyField(blank=True, to='bot.Launch')),
            ],
            bases=('bot.agency',),
        ),
        migrations.AddField(
            model_name='rocket',
            name='launches',
            field=models.ManyToManyField(blank=True, to='bot.Launch'),
        ),
        migrations.AddField(
            model_name='mission',
            name='launch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='bot.Launch'),
        ),
        migrations.AddField(
            model_name='location',
            name='launch',
            field=models.ManyToManyField(blank=True, to='bot.Launch'),
        ),
        migrations.AddField(
            model_name='agency',
            name='locations',
            field=models.ManyToManyField(blank=True, to='bot.Location'),
        ),
        migrations.AddField(
            model_name='agency',
            name='pads',
            field=models.ManyToManyField(blank=True, to='bot.Pad'),
        ),
        migrations.AddField(
            model_name='agency',
            name='rockets',
            field=models.ManyToManyField(blank=True, to='bot.Rocket'),
        ),
    ]
