# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_auto_20171106_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agency',
            options={'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AlterModelOptions(
            name='dailydigestrecord',
            options={'verbose_name': 'Daily Digest - Record', 'verbose_name_plural': 'Daily Digest - Records'},
        ),
        migrations.AlterModelOptions(
            name='launch',
            options={'verbose_name': 'Launch', 'verbose_name_plural': 'Launches'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='lsp',
            options={'verbose_name': 'LSP', 'verbose_name_plural': 'LSPs'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Mission', 'verbose_name_plural': 'Missions'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='pad',
            options={'verbose_name': 'Pad', 'verbose_name_plural': 'Pads'},
        ),
        migrations.AlterModelOptions(
            name='rocket',
            options={'verbose_name': 'Rocket', 'verbose_name_plural': 'Rockets'},
        ),
        migrations.AlterModelOptions(
            name='vidurls',
            options={'verbose_name': 'Video URL', 'verbose_name_plural': 'Video URLs'},
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedOneHourTwitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedTenMinutesTwitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedTwentyFourHourTwitter',
            field=models.BooleanField(default=False),
        ),
    ]
