# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-22 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_auto_20190720_2004'),
        ('bot', '0010_auto_20190722_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=16)),
                ('message', models.TextField(max_length=25)),
                ('send_ios', models.BooleanField(default=False)),
                ('send_ios_complete', models.NullBooleanField(default=False)),
                ('send_android', models.BooleanField(default=False)),
                ('send_android_complete', models.NullBooleanField(default=False)),
                ('event', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='api.Events')),
                ('launch', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='api.Launch')),
                ('news', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, to='bot.NewsItem')),
            ],
        ),
    ]
