# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_auto_20171114_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
