# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_notification_last_notification_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_notification_recipient_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
