# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-26 01:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_notification_last_notification_recipient_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='net',
            field=models.DateTimeField(default=datetime.tzinfo, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='window_end',
            field=models.DateTimeField(default=datetime.tzinfo, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='window_start',
            field=models.DateTimeField(default=datetime.tzinfo, max_length=255, null=True),
        ),
    ]
