# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-28 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_auto_20190928_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='news', to='api.Events'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='launches',
            field=models.ManyToManyField(blank=True, related_name='news', to='api.Launch'),
        ),
    ]
