# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-26 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20180625_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_url', models.URLField()),
            ],
            options={
                'verbose_name': 'Info URL',
                'verbose_name_plural': 'Info URLs',
            },
        ),
        migrations.AddField(
            model_name='launch',
            name='failreason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='launch',
            name='hashtag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='launch',
            name='holdreason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='launch',
            name='isoend',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='isonet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='isostart',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='probability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='launch',
            name='tbddate',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='launch',
            name='tbdtime',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='launch',
            name='inhold',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='infourls',
            name='launch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_urls', to='bot.Launch'),
        ),
    ]
