# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-05 18:47
from __future__ import unicode_literals

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models
import django.db.models.deletion


def seed_article(apps, schema_editor):
    news_model = apps.get_model('bot', 'newsitem')
    article_model = apps.get_model('api', 'article')
    article_notification_model = apps.get_model('bot', 'articlenotification')

    for news_item in news_model.objects.all():
        article, created = article_model.objects.get_or_create(
            id=news_item.id,
            title=news_item.title,
            link=news_item.link,
            description=news_item.description,
            featured_image=news_item.featured_image,
            news_site=news_item.news_site,
            created_at=news_item.created_at,
        )
        if len(news_item.events.all()) > 0:
            events = news_item.events.all()
            article.events.add(*events)
        if len(news_item.launches.all()) > 0:
            launches = news_item.launches.all()
            article.launches.add(*launches)
        article.save()

    article_model = apps.get_model('api', 'article')
    for article in article_model.objects.all():
        news_item = news_model.objects.get(id=article.id)
        article_notification, created = article_notification_model.objects.get_or_create(
            id=news_item.id,
            article=article,
            read=news_item.read,
            should_notify=news_item.should_notify,
            was_notified=news_item.was_notified,
        )
        article_notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_article'),
        ('bot', '0014_auto_20190928_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleNotification',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('should_notify', models.BooleanField(default=False)),
                ('was_notified', models.BooleanField(default=False)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Article')),
            ],
        ),
        migrations.RunPython(code=seed_article),
    ]
