# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-02 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_auto_20180701_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='info_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agency',
            name='wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pad',
            name='info_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pad',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pad',
            name='wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
