# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20180626_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launch',
            name='net',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='window_end',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='launch',
            name='window_start',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
