# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-08-05 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_articlenotifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='events',
        ),
        migrations.RemoveField(
            model_name='newsitem',
            name='launches',
        ),
        migrations.AlterField(
            model_name='notification',
            name='news',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Article'),
        ),
        migrations.DeleteModel(
            name='NewsItem',
        ),
    ]
