# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-04 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_auto_20180702_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='location',
        ),
        migrations.AddField(
            model_name='pad',
            name='location',
            field=models.ManyToManyField(to='bot.Location'),
        ),
    ]
