# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-26 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


def rebuild_fk(apps, schema_editor):
    records = apps.get_model('bot', 'launchnotificationrecord')
    for record in records.objects.all():
        if record.launch is not None:
            record.migrate_launch_id = record.launch.id
            record.save()
        else:
            record.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20200805_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='launchnotificationrecord',
            name='migrate_launch_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.RunPython(code=rebuild_fk),
    ]
