# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-04 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_auto_20180703_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pad',
            name='location',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='pads',
        ),
        migrations.AddField(
            model_name='location',
            name='info_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='pad_name',
            field=models.CharField(blank=True, default=b'', max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='wiki_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Pad',
        ),
    ]
