# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-26 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_launchnotificationrecord_migrate_launch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launchnotificationrecord',
            name='launch',
        ),
    ]
