# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-26 04:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_remove_launchnotificationrecord_launch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='launchnotificationrecord',
            old_name='migrate_launch_id',
            new_name='launch_id',
        ),
    ]
