# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_auto_20180705_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default=b'', max_length=255)),
                ('info_url', models.URLField(blank=True)),
                ('wiki_url', models.URLField(blank=True)),
                ('map_url', models.URLField(blank=True)),
                ('agency_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Pad',
                'verbose_name_plural': 'Pads',
            },
        ),
        migrations.RenameField(
            model_name='location',
            old_name='pad_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='info_url',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='map_url',
        ),
        migrations.RemoveField(
            model_name='location',
            name='pad_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='wiki_url',
        ),
        migrations.AddField(
            model_name='location',
            name='pad',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.Pad'),
            preserve_default=False,
        ),
    ]
