# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0022_auto_20180705_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='pads',
            field=models.ManyToManyField(blank=True, to='bot.Pad'),
        ),
    ]
