# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0023_agency_pads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pad',
            name='location',
        ),
        migrations.AddField(
            model_name='launch',
            name='pad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pad', to='bot.Pad'),
        ),
        migrations.AddField(
            model_name='location',
            name='pad',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='location_pad', to='bot.Pad'),
            preserve_default=False,
        ),
    ]
