# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0024_auto_20180705_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='pad',
        ),
        migrations.AddField(
            model_name='pad',
            name='location',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pad', to='bot.Location'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='launch',
            name='lsp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='bot.LSP'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='bot.Mission'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='pad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='bot.Pad'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='rocket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='launch', to='bot.Rocket'),
        ),
    ]
