# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0027_auto_20180705_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='launch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Launch'),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='InfoURLs',
        ),
        migrations.DeleteModel(
            name='Launch',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LSP',
        ),
        migrations.DeleteModel(
            name='Mission',
        ),
        migrations.DeleteModel(
            name='Pad',
        ),
        migrations.DeleteModel(
            name='Rocket',
        ),
        migrations.DeleteModel(
            name='VidURLs',
        ),
    ]
