# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-01 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0028_auto_20180705_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedInFlightDiscord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedOneHourDiscord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedOneMinutesDiscord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedTenMinutesDiscord',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedTwentyFourHourDiscord',
            field=models.BooleanField(default=False),
        ),
    ]
