# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-01 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0029_auto_20180831_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedSuccessDiscord',
            field=models.BooleanField(default=False),
        ),
    ]
