# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-01 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0031_discordchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordchannel',
            name='server_id',
            field=models.CharField(max_length=4000),
        ),
    ]
