# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-16 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0032_auto_20180901_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='last_net_stamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
