# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0033_auto_20180916_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedInFlight',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedInFlightTwitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedOneMinute',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedOneMinuteTwitter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedSuccess',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='wasNotifiedSuccessTwitter',
            field=models.BooleanField(default=False),
        ),
    ]
