# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-25 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_auto_20181025_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('featured_image', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('news_site', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewsNotificationChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=4000, unique=True)),
                ('server_id', models.CharField(max_length=4000)),
                ('name', models.CharField(max_length=4000)),
                ('subscribed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'News Notification Channels',
                'verbose_name': 'News Notification Channel',
            },
        ),
    ]
