# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-23 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_auto_20181022_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterNotificationChannel',
            fields=[
                ('discordchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot.DiscordChannel')),
            ],
            options={
                'verbose_name': 'Twitter Notification Channel',
                'verbose_name_plural': 'Twitter Notification Channels',
            },
            bases=('bot.discordchannel',),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='subscribers',
            field=models.ManyToManyField(to='bot.TwitterNotificationChannel'),
        ),
    ]
