# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-25 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0035_auto_20181025_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditsubmission',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='redditsubmission',
            name='text',
            field=models.CharField(blank=True, default='', max_length=40000, null=True),
        ),
    ]
