# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-24 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0038_twitteruser_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
