# External Secret for Grafana Admin Credentials
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-credentials
  namespace: metrics
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: grafana-admin-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      type: Opaque
      data:
        admin-user: "{{ .admin_user }}"
        admin-password: "{{ .admin_password }}"
  data:
  - secretKey: admin_user
    remoteRef:
      key: grafana
      property: admin-user
  - secretKey: admin_password
    remoteRef:
      key: grafana
      property: admin-password
