# Secrets Configuration for SpaceLaunchNow
# This file defines all secrets that should be created in Vault
# The deploy.sh script will read this file and create/update secrets automatically

secrets:
  # SpaceLaunchNow Development Environment
  sln-app-dev:
    path: "secret/sln-app-dev"
    description: "SpaceLaunchNow development environment secrets"
    data:
      django-secret-key: "dev-django-secret-key-placeholder"
      database-username: "spacelaunchnow_dev"
      database-password: "dev-database-password-placeholder"
      database-host: "postgresql-dev.example.com"
      database-port: "5432"
      aws-access-key-id: "dev-aws-access-key-placeholder"
      aws-secret-access-key: "dev-aws-secret-key-placeholder"
      do-cluster-id: "dev-cluster-id-placeholder"
      do-token: "dev-do-token-placeholder"
      email-host-user: "noreply@spacelaunchnow.app"
      email-host-password: "dev-email-password-placeholder"
      google-api-key: "dev-google-api-key-placeholder"
      google-analytics-tracking-id: "GA-XXXXXXXX-X"
      token-key: "dev-token-key-placeholder"
      token-secret: "dev-token-secret-placeholder"
      consumer-key: "dev-consumer-key-placeholder"
      consumer-secret: "dev-consumer-secret-placeholder"
      fcm-key: "dev-fcm-key-placeholder"
      fcm-project-id: "spacelaunchnow-dev"
      fcm-credentials: "dev-fcm-credentials-json-placeholder"
      discord-webhook: "https://discord.com/api/webhooks/dev-webhook-placeholder"
      discord-webhook-notification: "https://discord.com/api/webhooks/dev-notification-placeholder"
      sln-sentry-key: "https://dev123placeholder@o123456.ingest.sentry.io/7891011"

  # SpaceLaunchNow Production Environment
  sln-app:
    path: "secret/sln-app"
    description: "SpaceLaunchNow production environment secrets"
    data:
      django-secret-key: "prod-django-secret-key-placeholder"
      database-username: "spacelaunchnow_prod"
      database-password: "prod-database-password-placeholder"
      database-host: "postgresql-prod.example.com"
      database-port: "5432"
      aws-access-key-id: "prod-aws-access-key-placeholder"
      aws-secret-access-key: "prod-aws-secret-key-placeholder"
      do-cluster-id: "prod-cluster-id-placeholder"
      do-token: "prod-do-token-placeholder"
      email-host-user: "noreply@spacelaunchnow.app"
      email-host-password: "prod-email-password-placeholder"
      google-api-key: "prod-google-api-key-placeholder"
      google-analytics-tracking-id: "GA-XXXXXXXX-Y"
      token-key: "prod-token-key-placeholder"
      token-secret: "prod-token-secret-placeholder"
      consumer-key: "prod-consumer-key-placeholder"
      consumer-secret: "prod-consumer-secret-placeholder"
      fcm-key: "prod-fcm-key-placeholder"
      fcm-project-id: "spacelaunchnow-prod"
      fcm-credentials: "prod-fcm-credentials-json-placeholder"
      discord-webhook: "https://discord.com/api/webhooks/prod-webhook-placeholder"
      discord-webhook-notification: "https://discord.com/api/webhooks/prod-notification-placeholder"
      sln-sentry-key: "https://prod456placeholder@o123456.ingest.sentry.io/7891012"

  # Cloudflare for cert-manager
  cloudflare:
    path: "secret/cloudflare"
    description: "Cloudflare API token for SSL certificate management"
    data:
      api_token: "cloudflare-api-token-placeholder"
      
  # Example: Adding a new service secret
  # my-new-service:
  #   path: "secret/my-new-service"
  #   description: "Secrets for my new service"
  #   data:
  #     database_url: "postgresql://user:pass@host:5432/db"
  #     api_key: "my-service-api-key"
  #     webhook_secret: "webhook-secret-value"
