# SecretStore that connects External Secrets Operator to Vault for sln-dev namespace
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: sln-dev
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets"
          serviceAccountRef:
            name: "external-secrets-sa"

---
# ExternalSecret for SpaceLaunchNow application secrets in sln-dev namespace
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sln-auth-dev
  namespace: sln-dev
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: sln-auth-dev
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  # Django Configuration
  - secretKey: django-secret-key
    remoteRef:
      key: sln-app-dev
      property: django-secret-key
  
  # AWS Configuration
  - secretKey: aws-access-key-id
    remoteRef:
      key: sln-app-dev
      property: aws-access-key-id
  - secretKey: aws-secret-access-key
    remoteRef:
      key: sln-app-dev
      property: aws-secret-access-key
  
  # DigitalOcean Configuration
  - secretKey: do-cluster-id
    remoteRef:
      key: sln-app-dev
      property: do-cluster-id
  - secretKey: do-token
    remoteRef:
      key: sln-app-dev
      property: do-token
  
  # Database Configuration
  - secretKey: database-username
    remoteRef:
      key: sln-app-dev
      property: database-username
  - secretKey: database-password
    remoteRef:
      key: sln-app-dev
      property: database-password
  - secretKey: database-host
    remoteRef:
      key: sln-app-dev
      property: database-host
  - secretKey: database-port
    remoteRef:
      key: sln-app-dev
      property: database-port
  
  # Email Configuration
  - secretKey: email-host-user
    remoteRef:
      key: sln-app-dev
      property: email-host-user
  - secretKey: email-host-password
    remoteRef:
      key: sln-app-dev
      property: email-host-password
  
  # Google Configuration
  - secretKey: google-api-key
    remoteRef:
      key: sln-app-dev
      property: google-api-key
  - secretKey: google-analytics-tracking-id
    remoteRef:
      key: sln-app-dev
      property: google-analytics-tracking-id
  
  # Twitter/X Configuration
  - secretKey: token-key
    remoteRef:
      key: sln-app-dev
      property: token-key
  - secretKey: token-secret
    remoteRef:
      key: sln-app-dev
      property: token-secret
  - secretKey: consumer-key
    remoteRef:
      key: sln-app-dev
      property: consumer-key
  - secretKey: consumer-secret
    remoteRef:
      key: sln-app-dev
      property: consumer-secret
  
  # Discord Configuration
  - secretKey: discord-webhook
    remoteRef:
      key: sln-app-dev
      property: discord-webhook
  - secretKey: discord-webhook-notification
    remoteRef:
      key: sln-app-dev
      property: discord-webhook-notification
  
  # Firebase/FCM Configuration
  - secretKey: fcm-project-id
    remoteRef:
      key: sln-app-dev
      property: fcm-project-id
  - secretKey: fcm-credentials
    remoteRef:
      key: sln-app-dev
      property: fcm-credentials
  - secretKey: fcm-key
    remoteRef:
      key: sln-app-dev
      property: fcm-key
