# SpaceLaunchNow Secrets Management Configuration
# This values file consolidates all secrets management configuration into one place

# Global settings
global:
  domain: spacelaunchnow.app

# SpaceLaunchNow Application Secrets Configuration
secrets:
  # Development Environment Secrets
  dev:
    vaultPath: "secret/sln-app-dev"
    secretName: "sln-auth-dev"
    namespace: "sln-dev"
    credentials:
      # Django Configuration
      django-secret-key: "dev-django-secret-key-placeholder"
      
      # Database Configuration
      database-username: "spacelaunchnow_dev"
      database-password: "dev-database-password-placeholder"
      database-host: "postgresql-dev.example.com"
      database-port: "5432"
      
      # AWS Configuration
      aws-access-key-id: "dev-aws-access-key-placeholder"
      aws-secret-access-key: "dev-aws-secret-key-placeholder"
      
      # DigitalOcean Configuration
      do-cluster-id: "dev-cluster-id-placeholder"
      do-token: "dev-do-token-placeholder"
      
      # Email Configuration
      email-host-user: "noreply@spacelaunchnow.app"
      email-host-password: "dev-email-password-placeholder"
      
      # Google Services
      google-api-key: "dev-google-api-key-placeholder"
      google-analytics-tracking-id: "GA-XXXXXXXX-X"
      
      # Social Authentication
      token-key: "dev-token-key-placeholder"
      token-secret: "dev-token-secret-placeholder"
      consumer-key: "dev-consumer-key-placeholder"
      consumer-secret: "dev-consumer-secret-placeholder"
      
      # Firebase Cloud Messaging
      fcm-key: "dev-fcm-key-placeholder"
      fcm-project-id: "spacelaunchnow-dev"
      fcm-credentials: "dev-fcm-credentials-json-placeholder"
      
      # Discord Webhooks
      discord-webhook: "https://discord.com/api/webhooks/dev-webhook-placeholder"
      discord-webhook-notification: "https://discord.com/api/webhooks/dev-notification-placeholder"
      
      # Error Tracking
      sln-sentry-key: "https://dev123placeholder@o123456.ingest.sentry.io/7891011"

  # Production Environment Secrets
  prod:
    vaultPath: "secret/sln-app"
    secretName: "sln-auth-prod"
    namespace: "sln-prod"
    credentials:
      # Django Configuration
      django-secret-key: "prod-django-secret-key-placeholder"
      
      # Database Configuration
      database-username: "spacelaunchnow_prod"
      database-password: "prod-database-password-placeholder"
      database-host: "postgresql-prod.example.com"
      database-port: "5432"
      
      # AWS Configuration
      aws-access-key-id: "prod-aws-access-key-placeholder"
      aws-secret-access-key: "prod-aws-secret-key-placeholder"
      
      # DigitalOcean Configuration
      do-cluster-id: "prod-cluster-id-placeholder"
      do-token: "prod-do-token-placeholder"
      
      # Email Configuration
      email-host-user: "noreply@spacelaunchnow.app"
      email-host-password: "prod-email-password-placeholder"
      
      # Google Services
      google-api-key: "prod-google-api-key-placeholder"
      google-analytics-tracking-id: "GA-XXXXXXXX-Y"
      
      # Social Authentication
      token-key: "prod-token-key-placeholder"
      token-secret: "prod-token-secret-placeholder"
      consumer-key: "prod-consumer-key-placeholder"
      consumer-secret: "prod-consumer-secret-placeholder"
      
      # Firebase Cloud Messaging
      fcm-key: "prod-fcm-key-placeholder"
      fcm-project-id: "spacelaunchnow-prod"
      fcm-credentials: "prod-fcm-credentials-json-placeholder"
      
      # Discord Webhooks
      discord-webhook: "https://discord.com/api/webhooks/prod-webhook-placeholder"
      discord-webhook-notification: "https://discord.com/api/webhooks/prod-notification-placeholder"
      
      # Error Tracking
      sln-sentry-key: "https://prod456placeholder@o123456.ingest.sentry.io/7891012"

# OIDC Configuration for Vault
oidc:
  enabled: true
  google:
    clientId: "your-google-oauth-client-id"
    clientSecret: "your-google-oauth-client-secret"
    restrictedEmail: "ca.jones9119@gmail.com"

# Vault Policies and Roles
vaultConfig:
  policies:
    admin-restricted:
      path: "secret/*"
      capabilities: ["create", "read", "update", "delete", "list"]
      
  secretStores:
    - name: "vault-backend"
      namespace: "sln-dev"
    - name: "vault-backend" 
      namespace: "sln-prod"

# Initialization settings
initialization:
  # Set to true to populate Vault with initial placeholder secrets
  populateSecrets: true
  
  # Set to true to create OIDC authentication
  setupOIDC: true
  
  # Set to true to create service accounts and RBAC
  setupServiceAccounts: true
