# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landinglocation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='landingtype',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
