# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_auto_20180827_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='landinglocation',
            name='abbrev',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='landinglocation',
            name='description',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='landingtype',
            name='abbrev',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
