# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-19 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0003_auto_20180827_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstStageType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
