# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0004_firststagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstronautStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Astronaut Status',
                'verbose_name_plural': "Astronaut Status'",
            },
        ),
        migrations.CreateModel(
            name='OrbiterStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Orbiter Status',
                'verbose_name_plural': "Orbiter Status'",
            },
        ),
        migrations.CreateModel(
            name='SpaceStationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Space Station Status',
                'verbose_name_plural': "Space Station Status'",
            },
        ),
    ]
