# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0006_auto_20181205_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='AstronautRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Astronaut Role',
                'verbose_name_plural': 'Astronaut Roles',
            },
        ),
    ]
