# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_astronauttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceStationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Space Station Types',
                'verbose_name': 'Space Station Type',
            },
        ),
    ]
