# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-22 22:01
from __future__ import unicode_literals

from django.db import migrations, models


def add_default(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    SpaceStationType = apps.get_model("configurations", "SpaceStationType")
    SpaceStationType.objects.using(db_alias).create(id=1, name="Unknown")
    SpaceStationType.objects.using(db_alias).create(id=2, name="Government")
    SpaceStationType.objects.using(db_alias).create(id=3, name="Commercial")

class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0011_spacestationtype'),
    ]

    operations = [
        migrations.RunPython(add_default),
    ]
