# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-25 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20190324_1353'),
        ('configurations', '0013_eventtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockinglocation',
            name='spacestation',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='docking_location', to='api.SpaceStation'),
        ),
    ]
