---
name: Cached Python and Poetry setup
description: Cache Poetry with additional extras key

inputs:
  python-version:
    description: >
      Version range or exact version of a Python version to use, using SemVer's version range syntax.
    required: false
    default: 3.12.4
  repo_username:
    description: TSD pypi username
    required: true
  repo_password:
    description: TSD pypi password
    required: true

outputs:
  python-version:
    description: The installed python version. Useful when given a version range as input.
    value: ${{ steps.setup-python.outputs.python-version }}

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry
      shell: bash
      run: curl -sSL https://install.python-poetry.org | python3 - --version 1.8.3
    - name: Install poetry dependencies
      shell: bash
      run: |
        export POETRY_HTTP_BASIC_TSD_USERNAME=${{inputs.repo_username}}
        export POETRY_HTTP_BASIC_TSD_PASSWORD=${{inputs.repo_password}}
        poetry install --all-extras --with dev
