---
name: Python Test
description: Run Django Test and (optionally) upload coverage as a GitHub artifact

inputs:
  upload-coverage:
    description: Whether coverage should be uploaded as an artifact.
    default: true
  upload-test-report:
    description: Whether HTML test report should be uploaded as an artifact.
    default: true

outputs:
  coverage-name:
    description: Name of the uploaded coverage artifact
    value: ${{ inputs.artifact-name }}
  upload-coverage:
    description: Whether coverage was uploaded as an artifact.
    value: ${{ inputs.upload-coverage }}
  test-report-name:
    description: Name of the uploaded HTML test report
    value: ${{ inputs.test-report-name }}
  upload-test-report:
    description: Whether HTML test report should be uploaded as an artifact.
    value: ${{ inputs.upload-test-report }}

runs:
  using: composite
  steps:
    - name: Run Test Suite
      shell: bash
      run: docker-compose -f docker/docker-compose.test.yml run test
    - name: Upload Coverage Data
      if: inputs.upload-coverage
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3.1.1
      with:
        name: coverage-data
        path: report/coverage/.coverage
    - name: Publish Coverage Report
      if: inputs.upload-test-report
      uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb # tag=v3.1.1
      with:
        name: coverage-report
        path: report/htmlcov
    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: 'report/xmlrunner/*.xml'
