apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django.fullname" . }}
  labels:
    {{- include "django.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $k, $v := .Values.env.secret }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
{{- if .Values.redis.enabled }}
  REDIS_URL: {{ include "django.redis.url" . | b64enc | quote }}
{{- end }}