name: Python Tests

on:
  pull_request:
    branches:
      - "**"
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - poetry.lock
        
env:
  POETRY_HTTP_BASIC_TSD_USERNAME: ${{ secrets.PRIVATE_USERNAME }}
  POETRY_HTTP_BASIC_TSD_PASSWORD: ${{ secrets.PRIVATE_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run Python Tests
        uses: ./.github/actions/python-test